### ISSUE TITLE
still under development?

### ISSUE THREAD

**Issue by kurt-o-sys** [aaronc/freactive#37]
freactive looks really awesome... however, I just wonder if it's still actively being developed. Checking out the 'list-view', it seems it's for a few months 'experimental'. Since I like it pretty much so far - I'm just trying it out - having a production-ready freactive some moment not years in the future would be amazing.

**Comment by aaronc** [comment]
Yes, freactive is still under active development - see the develop branch which has more recent commits. The plan is now to have a production ready release by around summer time. That could change, but as of now, I'm still planning on implementing the pending features... there's a development timeline I'm working against which has various priorities which will dictate exactly what happens when...

**Comment by kurt-o-sys** [comment]
Allright great! I missed the development branch... My bad.
